from pathlib import Path

p = Path('dist')
pages = [('Home', ''), ('Documentaries', 'films'), ('Photography', 'photography'), ('Impact', 'conservation'), ('Projects', 'collaborations'), ('About', 'about'), ('Speaking', 'speaking'), ('Fine Art Prints', 'prints'), ('Contact', 'contact')]
nav = ''.join(f'<a href="{("/" + slug + "/") if slug else "/"}">{name}</a>' for name, slug in pages)

def doc(title, body):
    footer = '''<footer class="cinematic-footer"><div class="cinematic-footer-main"><div class="footer-signature"><small>THE DREAMER / RABII BEN BRAHIM</small><h2>Keep looking<br>closer.</h2><p>Films and photographs from Tunisia, its wildlife and the people connected to place.</p><a href="/contact/">Start a conversation ↗</a></div><div class="footer-column"><small>EXPLORE</small><a href="/films/">Documentaries</a><a href="/photography/">Photography</a><a href="/conservation/">Impact</a><a href="/collaborations/">Projects</a><a href="/about/">About</a><a href="/speaking/">Speaking</a></div><div class="footer-column"><small>SELECTED FILMS</small><a href="https://www.youtube.com/watch?v=oBRHiGLC0S4" target="_blank" rel="noopener">Wildlife Wonders ↗</a><a href="https://www.youtube.com/watch?v=OyaSu8oF-D8" target="_blank" rel="noopener">Blue Future ↗</a><a href="https://ykone.com/portfolio/landrover-defender/" target="_blank" rel="noopener">Land Rover Defender ↗</a><a href="https://youtu.be/dT68BX8jonk" target="_blank" rel="noopener">Sadeem ↗</a><a href="https://youtu.be/5ZJtvU-VOjw" target="_blank" rel="noopener">Radio Cap FM ↗</a></div><div class="footer-column"><small>FOLLOW</small><a href="https://www.instagram.com/thedreamerwildandfree/" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.youtube.com/@thedreamerwildandfree" target="_blank" rel="noopener">YouTube ↗</a><a href="https://www.linkedin.com/in/rabii-ben-brahim-007309141" target="_blank" rel="noopener">LinkedIn ↗</a><a href="/prints/">Fine Art Prints</a><a href="/contact/">Contact</a></div></div><div class="cinematic-footer-bottom"><span>© 2026 THE DREAMER · RABII BEN BRAHIM</span><span>FILMS / PHOTOGRAPHY / CONSERVATION</span><a class="footer-credit" href="https://auradigitalworks.com/" target="_blank" rel="noopener noreferrer">Made by AuraDigital ↗</a><a href="/">BACK TO THE BEGINNING ↑</a></div></footer>'''
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} | The Dreamer</title><meta name="description" content="Rabii Ben Brahim — The Dreamer. Film, photography and conservation stories from Tunisia."><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/style.css"></head><body class="{'home-page' if title == 'Home' else 'inner-page'}"><header><a class="logo" href="/"><img src="/assets/logo.png" alt="The Dreamer"></a><button id="menu" aria-label="Toggle menu" aria-expanded="false">Menu ☰</button><nav aria-label="Main navigation">{nav}</nav></header><main>{body}</main>{footer}<script src="/site.js"></script></body></html>'''

for _, slug in pages:
    (p / slug).mkdir(parents=True, exist_ok=True)
exec(Path('content.py').read_text())
exec(Path('enhance.py').read_text())
