from html import escape
IG='https://www.instagram.com/thedreamerwildandfree/'
S={
 'story':'https://www.arabnews.fr/culture/rabii-ben-brahim-the-dreamer-une-mission-de-vie-au-service-de-lenvironnement-194521',
 'tourism':'https://www.discovertunisia.com/en/success-stories/rabii-ben-brahim',
 'wildlife':'https://www.linkedin.com/posts/rabii-ben-brahim-007309141_wildlife-wonders-activity-7311423928600596482-iWgy',
 'blue':'https://www.wwf.it/area-stampa/blue-future-il-documentario-wwf-sui-lavori-blu/',
 'defender':'https://ykone.com/portfolio/landrover-defender/',
 'ted':'https://www.ted.com/talks/rabii_ben_brahim_what_i_can_do_in_tunisia',
 'screening':'https://jninetelhafsia.bluefish.me/',
 'iucn':'https://iucn.org/our-work/region/mediterranean/our-work/biodiversity-knowledge-and-action/biodiversity-standards-and-indicators/mediterranean-green-list-protected-and-conserved-areas',
 'jet':'https://www.eumedbridge.eu/news/jet-cinema-2026-in-zaghouan-and-jendouba-cinema-comes-to-meet-territories-generations-and-imaginations/',
 'wwf_story':'https://www.wwf.tn/espace_medias/news_blogs/wall_of_fame_the_dreamer/'
}
def ext(url,label='View project'):
 return f'<a class="link" href="{escape(url)}" target="_blank" rel="noopener noreferrer">{escape(label)} ↗</a>'
def lead(kicker,title,desc):
 return f'<section class="pagehead minimal-head"><small>{kicker}</small><h1>{title}</h1><p class="lead">{desc}</p></section>'
photos=[('/assets/ain-draham.jpg','Aïn Draham forest, Tunisia','Smailtn · CC0', 'https://commons.wikimedia.org/wiki/File:Forest_A%C3%AFn_Draham.jpg'),('/assets/tunisian-sahara.jpg','Sahara Desert, Tunisia','Yee Tung Eleanor Chan · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Tunisian_Sahara_Desert_in_a_46%C2%B0c_afternoon.jpg'),('/assets/ichkeul-lake.jpg','Ichkeul, Tunisia','Pa681998 · CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Lake_Ichkeul.jpg')]
def landscape(i):
 src,place,credit,url=photos[i%len(photos)]
 return f'<img loading="lazy" src="{src}" alt="{place}"><a class="image-credit" href="{url}" target="_blank" rel="noopener">{place} · {credit} · editorial image ↗</a>'
def film_player(video_id,title):
 return f'<div class="film-player"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/{video_id}?autoplay=1&amp;mute=1&amp;playsinline=1&amp;loop=1&amp;playlist={video_id}&amp;rel=0" title="{escape(title)}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div>'
def feature(title,text,url,imgnum,tag):
 media=film_player('oBRHiGLC0S4','Wildlife Wonders by The Dreamer') if title=='Wildlife Wonders' else film_player('OyaSu8oF-D8','Blue Future trailer')
 return f'<article class="research-feature"><div class="research-image actual-film">{media}<span>ORIGINAL FILM / OFFICIAL PLAYER</span></div><div class="research-copy"><small>{tag}</small><h2>{title}</h2><p>{text}</p>{ext(url,"Credits & details")}</div></article>'
def simple(title,desc,url,tag):
 return f'<article class="research-row"><small>{tag}</small><div><h3>{title}</h3><p>{desc}</p></div>{ext(url,"Source & details")}</article>'
def visual(i,title,subtitle):
 src,place,credit,url=photos[i%len(photos)]
 return f'<figure class="card"><img loading="lazy" src="{src}" alt="{place}"><figcaption><b>{title}</b><span>{subtitle}</span><a href="{url}" target="_blank" rel="noopener">{place} · {credit} ↗</a></figcaption></figure>'
def reel(title, video_id, label, source):
 return f'<section class="screening"><div class="screening-title"><small>{label}</small><h2>{title}</h2>{ext(source,"Project credits")}</div><div class="screening-media">{film_player(video_id,title)}</div></section>'
def media_pair(left,right):
 return f'<div class="minimal-pair visual-pair">{left}{right}</div>'
def section(kicker,title,body):return f'<section class="research-section"><small>{kicker}</small><h2>{title}</h2>{body}</section>'
source_note='<p class="source-note">Project descriptions are based on publicly available credits. Editorial landscape images in this preview are illustrative; they are not attributed to Rabii.</p>'
home=f'''<section class="hero"><video class="hero-film" autoplay muted loop playsinline preload="metadata" poster="/assets/dreamer-hero-poster.jpg" aria-hidden="true" tabindex="-1"><source src="/assets/dreamer-hero.webm" type="video/webm"></video><a class="scroll" href="#story">Scroll to explore ↓</a></section>
<section id="story" class="intro section"><div><small>01 / THE STORY</small><h2>It began with curiosity.</h2></div><div><p>Rabii’s curiosity began with documentaries and conversations with his father. Exploring Tunisia with a camera became a way to share its overlooked places.</p><p class="secondary">Stories of nature, heritage and the people connected to both.</p><a class="link" href="/about/">Meet Rabii ↗</a></div></section>
<div class="gallery">{visual(0,'The forest','Aïn Draham · a landscape that shapes the story')}{visual(1,'The desert','Tunisian Sahara · a journey across the land')}{visual(2,'The wetland','Ichkeul · a place to see more closely')}</div>
{reel("Wildlife Wonders", "oBRHiGLC0S4", "WATCH / TUNISIA", S["wildlife"])}
<section class="statement"><small>THE VISION</small><h2>Make the living world visible. Give people a reason to care for it.</h2><p>Inspired by Rabii’s interviews about Tunisia’s natural and cultural heritage. {ext(S['story'],'Read his story')}</p></section>
{section('02 / FILMS','Stories in motion.',simple('Wildlife Wonders','A 2025 film on Tunisia’s natural heritage, produced by The Dreamer with wildlife ecologist Zakher Bouragaoui as part of the Tunisian Wonders project.',S['wildlife'],'2025 / TUNISIA')+simple('Blue Future','A WWF and COGITO collective documentary about sustainable livelihoods linked to the Mediterranean. Rabii was one of its filmmakers.',S['blue'],'2021 / MEDITERRANEAN'))}
{reel('Blue Future', 'OyaSu8oF-D8', 'WATCH / MEDITERRANEAN', S['blue'])}
{section('03 / COLLABORATIONS','Work made together.',simple('Land Rover Defender','A journey through Tunisia’s landscapes created with YKONE Tunis for the Defender launch.',S['defender'],'BRAND / TUNISIA')+simple('Wildlife Wonders','Developed with Zakher Bouragaoui; Rabii credits National Geographic support within the Tunisian Wonders initiative.',S['wildlife'],'CONSERVATION / FILM'))}
<section class="closing-cta"><small>KEEP EXPLORING</small><h2>See what the stories reveal.</h2><a class="link" href="/films/">Explore the films ↗</a><a class="link" href="/photography/">Explore photography ↗</a></section>'''
(p/'index.html').write_text(doc('Home',home))

films=lead('FILMS / DOCUMENTARIES','Stories that stay.','Film makes room for the landscapes, wildlife and human relationships behind each conservation story.')+section('SELECTED WORK','The films.',feature('Wildlife Wonders','A documentary about Tunisia’s natural heritage and conservation efforts. Produced by The Dreamer with Zakher Bouragaoui in 2025; Rabii describes it as supported through the National Geographic Explorer project Tunisian Wonders.',S['wildlife'],6,'2025 / TUNISIA')+feature('Blue Future','A collective documentary from WWF and COGITO following three Mediterranean stories across sustainable fishing, ecotourism and renewable energy. Rabii was among its four filmmakers; the Tunisian story follows Rania and ecotourism on the north coast.',S['blue'],3,'2021 / WWF & COGITO'))+media_pair(visual(0,'The forest','Aïn Draham · editorial image'),visual(1,'The desert','Tunisian Sahara · editorial image'))+section('WATCH / DISCOVER','From the source.',simple('Wildlife Wonders — film','Watch through the film link shared by Rabii.', 'https://www.youtube.com/watch?v=oBRHiGLC0S4','FILM')+simple('Blue Future — production details','Read the WWF credits and film background.',S['blue'],'PRODUCTION'))
(p/'films'/'index.html').write_text(doc('Films',films+source_note))
photography=lead('PHOTOGRAPHY','The art of paying attention.','From forest to desert and wetland, the landscapes in Rabii’s stories invite us to look closer. His original photographs are on his Instagram.')+f'<div class="gallery">{visual(0,"Aïn Draham","Editorial image of northwestern Tunisia · not Rabii’s photograph")}{visual(1,"The Sahara","Editorial image of southern Tunisia · not Rabii’s photograph")}{visual(2,"Ichkeul","Editorial image of the protected landscape · not Rabii’s photograph")}</div>'+section('THE ORIGINAL WORK','Follow the journey.','<p class="research-paragraph">The finished photography collection will use Rabii’s selected originals with locations, stories and individual image credits. Until those files are supplied, his public Instagram is the direct place to view his photographs.</p>'+ext(IG,'View Rabii’s Instagram'))
photography+=reel('Wildlife Wonders','oBRHiGLC0S4','RABII’S ORIGINAL FILM',S['wildlife'])
(p/'photography'/'index.html').write_text(doc('Photography',photography))
conservation=lead('CONSERVATION / IMPACT','A story can change what we protect.','Nature protection begins with attention: to species, to places, and to the communities that know them best.')+section('DOCUMENTED WORK','In the field.',simple('Wildlife Wonders','A film raising awareness of biodiversity and conservation in Tunisia, made with Zakher Bouragaoui.',S['wildlife'],'BIODIVERSITY')+simple('Blue Future','The Tunisian chapter highlights Rania’s ecotourism initiative and local livelihoods along the northern coast.',S['blue'],'MEDITERRANEAN')+simple('Protected areas','Rabii described filming work related to the IUCN Green List across Tunisia, Morocco, Lebanon and France in a 2022 interview. Project credits and footage still need confirmation.',S['story'],'INTERVIEW / 2022'))+f'<div class="wide-visual"><img src="/assets/ain-draham.jpg" alt="Aïn Draham forest in Tunisia"><a class="image-credit" href="https://commons.wikimedia.org/wiki/File:Forest_A%C3%AFn_Draham.jpg" target="_blank" rel="noopener">Aïn Draham · Smailtn · CC0 · editorial image ↗</a></div>'
conservation+=reel('Wildlife Wonders','oBRHiGLC0S4','BIODIVERSITY ON FILM',S['wildlife'])+media_pair(visual(2,'Ichkeul','Tunisia · editorial image'),visual(1,'The Sahara','Tunisia · editorial image'))
(p/'conservation'/'index.html').write_text(doc('Conservation',conservation))
collabs=lead('PROJECTS / COLLABORATIONS','Made with purpose.','Selected work across film, conservation and place-based storytelling. Each credit below is linked to its public source.')+section('SELECTED PARTNERSHIPS','The collaborations.',simple('WWF Mediterranean / COGITO','Rabii joined an international filmmaking team for Blue Future.',S['blue'],'DOCUMENTARY')+simple('YKONE Tunis / Land Rover Defender','Rabii featured in a visual road trip through Tunisia’s landscapes for the Defender launch.',S['defender'],'CAMPAIGN')+simple('Zakher Bouragaoui / Tunisian Wonders','Wildlife Wonders was produced with ecologist Zakher Bouragaoui; project support is described in Rabii’s published credit.',S['wildlife'],'WILDLIFE FILM')+simple('Jninet El Hafsia','The community garden hosted a public screening of Wildlife Wonders.',S['screening'],'SCREENING'))
collabs+=reel('Blue Future','OyaSu8oF-D8','WWF / COGITO',S['blue'])+media_pair(visual(0,'Tunisia','Aïn Draham · editorial image'),visual(1,'Across the land','Sahara · editorial image'))
(p/'collaborations'/'index.html').write_text(doc('Collaborations',collabs))
about=lead('ABOUT / RABII BEN BRAHIM','The Dreamer behind the lens.','A Tunisian filmmaker and explorer following the threads between nature, culture and the lives of people who belong to a place.')+f'<figure class="feature-image press-image"><img src="https://www.arabnews.fr/sites/default/files/styles/670x395/public/2022-01/1%20image0%20%283%29_0.jpeg?h=7262c4fb" alt="Rabii Ben Brahim pictured in Arab News"><figcaption>RABII BEN BRAHIM · <a href="{S['story']}" target="_blank" rel="noopener">PHOTO: ARAB NEWS EN FRANÇAIS ↗</a></figcaption></figure>'+section('THE BEGINNING','Curiosity became a journey.','<p class="research-paragraph">Rabii’s father introduced him to documentaries and encouraged his questions about the world. An uncle living close to the forest in northwestern Tunisia shaped his understanding of the relationship between people and nature. Rabii began exploring and sharing little-known places in Tunisia with a camera and backpack.</p>'+ext(S['story'],'Read Rabii’s interview'))+section('THE VISION','See a place. Understand its people.','<p class="research-paragraph">In an interview, Rabii described his mission as helping preserve Tunisia’s natural and cultural heritage. His stories move between mountains, forests, desert and coast, giving space to people whose knowledge and livelihoods are connected to those environments.</p>'+ext(S['tourism'],'Early journey'))
about+=media_pair(visual(0,'The forest','Northwestern Tunisia · editorial image'),visual(1,'The desert','Southern Tunisia · editorial image'))
(p/'about'/'index.html').write_text(doc('About',about))
speaking=lead('SPEAKING / MEDIA','A story beyond the screen.','Conversations about nature, film and what it means to see one’s own country with fresh eyes.')+section('SELECTED APPEARANCES','On stage and in conversation.',simple('TEDxDjerba — What I can do in Tunisia','Rabii spoke at TEDxDjerba in December 2017.',S['ted'],'TALK / 2017')+simple('Arab News en français — The Dreamer','An interview about his childhood, environmental mission and Mediterranean film work.',S['story'],'INTERVIEW / 2022')+simple('Wildlife Wonders — Jninet El Hafsia','An open-air screening of the documentary at the Tunis community garden.',S['screening'],'SCREENING / 2025'))
speaking+=media_pair(visual(0,'A journey begins','Aïn Draham · editorial image'),visual(2,'A place to protect','Ichkeul · editorial image'))
(p/'speaking'/'index.html').write_text(doc('Speaking & Media',speaking))
prints=lead('FINE ART PRINTS','Bring the story home.','A considered selection of photographs may become available as fine art prints.')+section('FUTURE COLLECTION','Selected by the artist.','<p class="research-paragraph">The print collection is in preparation. Editions, formats, prices and shipping details will be announced only when Rabii confirms the selected images and production details.</p>'+ext(IG,'Explore original photographs'))
prints+=media_pair(visual(0,'Forest study','Editorial image · not available as a Dreamer print'),visual(1,'Desert study','Editorial image · not available as a Dreamer print'))
(p/'prints'/'index.html').write_text(doc('Fine Art Prints',prints))
contact=lead('CONTACT / WORK WITH ME','Let’s tell the next story.','For films, conservation projects, creative partnerships, photography and speaking invitations.')+section('GET IN TOUCH','Find The Dreamer.',f'<p class="research-paragraph">For now, connect through Rabii’s public Instagram profile. A direct email address and inquiry form can be added once he confirms his preferred contact details.</p>{ext(IG,"Open Instagram")}')
contact+=media_pair(visual(0,'The landscape','Aïn Draham · editorial image'),visual(2,'The wetland','Ichkeul · editorial image'))
(p/'contact'/'index.html').write_text(doc('Contact',contact))
