"""Build The Dreamer's original editorial universe. Run from the repository root."""
from pathlib import Path
from html import escape as e
from PIL import Image,ImageOps
import json,re
ROOT=Path(__file__).resolve().parents[1]
ORIGIN='https://fifty.ink'
IG='https://www.instagram.com/thedreamerwildandfree/'
P=lambda n:'assets/photography/'+n+'.jpg'
D=lambda n:'assets/projects/djerba/'+n+'.webp'
PHOTO={
'645836414':('Last light over the herd','Elephants silhouetted against the setting sun','Wildlife'),
'650871801':('A closer look','Elephant standing in front of its herd','Wildlife'),
'649232440':('The sun between them','Elephant in the warm light of sunset','Wildlife'),
'650643519':('Under a changing sky','Elephant family beneath a broad clouded sky','Wildlife'),
'653507443':('The long walk','Young elephant walking across grassland','Wildlife'),
'469728961':('A face in the grass','Close portrait of a lion','Wildlife'),
'469683747':('A breath in the open air','Lion with its mouth open','Wildlife'),
'469825933':('Together','Two lions resting close together','Wildlife'),
'469728510':('In monochrome','Black and white lion portrait','Black & White'),
'573570378':('Watching, quietly','Leopard resting against a tree','Wildlife'),
'573688673':('The hidden world','Two views of leopards in the trees','Wildlife'),
'654066053':('An unguarded moment','Baboon opening its mouth','Wildlife'),
'556922215':('A small gaze','Owl sheltered in a rocky hollow','Wildlife'),
'556626056':('Shelter in stone','Owl standing in a rocky opening','Wildlife'),
'700708021':('A flash of colour','Colourful bird flying across a green background','Wildlife'),
'731067983':('Wings over water','Bird of prey flying against a pale sky','Wildlife'),
'731158290':('Across the blue','Bird in flight against a blue sky','Wildlife'),
'817329413':('The open sky','Bird flying against a clear sky','Wildlife'),
'821441541':('On the wing','Bird of prey in flight','Wildlife'),
'810813870':('Through the reeds','Dark bird among green reeds','Wildlife'),
'527337330':('At the water’s edge','Shorebird standing beside blue water','Wildlife'),
'575191913':('Wild colour','Bird photographs arranged in a supplied visual sequence','Wildlife'),
'555630946':('On the warm stone','Small reptile resting on sunlit rock','Wildlife'),
'555826408':('Almost invisible','Green lizard against the texture of rock','Wildlife'),
'557438021':('A patient perch','Bird perched among thin branches','Wildlife'),
'573551598':('A closer world','Reptile resting on a rocky ledge','Wildlife'),
'686509758':('Small worlds','Tiny insect on a green leaf','Wildlife'),
'684847033':('Another scale','Close view of a small creature on a leaf','Wildlife'),
'689096947':('Held in the light','Small insect against a dark background','Wildlife'),
'525861371':('Below the surface','Jellyfish against blue water','Wildlife'),
'526215548':('Where rock meets sea','Rocky coastline above clear turquoise water','Landscapes'),
'526763980':('A boat between worlds','Small boat beside shallow water and a rocky coast','Landscapes'),
'526594784':('One quiet crossing','Kayak seen from above in deep blue water','Landscapes'),
'525755603':('The coast opens out','High coastal cliffs beside the Mediterranean','Landscapes'),
'526506341':('A hidden cove','Aerial view of a rocky Mediterranean cove','Landscapes'),
'526744379':('Coastline in three frames','Three views of a rocky coastline','Landscapes'),
'526294068':('A line along the shore','Aerial view of rock, beach and clear water','Landscapes'),
'527055566':('Alone on the water','Single kayak on dark blue water','Landscapes'),
'526285315':('Behind the lens','Photographer in silhouette holding a camera','Behind the Lens'),
'573830916':('A field day in focus','Wildlife photographer with camera and binoculars','Behind the Lens'),
'556799051':('The making of a frame','Supplied sequence of owl, photographer and reptile images','Behind the Lens'),
'652760438':('Sharing a way of seeing','Camera work and people in the field','Behind the Lens'),
'651451626':('A quiet conversation','Two people seated beside a blue doorway','People'),
'645712006':('Under the tree','Person seated in the shade of a tree','People'),
'655487978':('Between conversations','Person standing near a bright blue doorway','People'),
'655081329':('A portrait in sunlight','Portrait of a man in a straw hat','People'),
'651912908':('Along the water','Person sitting beside the water','People'),
'653587851':('A day by the coast','Person standing beside fishing equipment','People'),
'651921257':('An encounter by the sea','Close view of a fish held near the coast','Conservation'),
'651876653':('Life and livelihood','Fish gathered in a shallow tray','Conservation'),
'650345189':('From the water','Fresh fish arranged together','Conservation'),
'526130764':('A place for wildlife','Bird standing at the edge of coastal rock','Conservation')}
# Keep every photograph even when the supplied archive expands.
for f in sorted((ROOT/'assets/photography').glob('*.jpg')):
 PHOTO.setdefault(f.stem,('From the field','Photograph from the supplied Dreamer archive','Wildlife'))
DERIV={}
for f in sorted((ROOT/'assets').rglob('*')):
 if f.suffix.lower() not in ('.jpg','.png','.webp') or 'editorial' in f.parts:continue
 im=ImageOps.exif_transpose(Image.open(f)).convert('RGB'); rel=f.relative_to(ROOT).as_posix();w,h=im.size
 variants=[]
 for width in sorted(set([min(w,480),min(w,960),min(w,1600)])):
  dest=ROOT/'assets/editorial'/f.relative_to(ROOT/'assets').with_suffix('')
  dest=Path(str(dest)+f'-{width}.webp');dest.parent.mkdir(parents=True,exist_ok=True)
  if not dest.exists():im.resize((width,round(h*width/w)),Image.Resampling.LANCZOS).save(dest,'WEBP',quality=85)
  variants.append((width,dest.relative_to(ROOT).as_posix()))
 DERIV[rel]=(w,h,variants)

def img(path,alt,cls='',eager=False):
 w,h,v=DERIV[path];src=v[-1][1];srcset=', '.join('/'+s+' '+str(n)+'w' for n,s in v)
 return f'<img class="{cls}" src="/{src}" srcset="{srcset}" sizes="(max-width: 760px) 92vw, 70vw" width="{w}" height="{h}" alt="{e(alt)}" loading="{"eager" if eager else "lazy"}" decoding="async"'+(' fetchpriority="high"' if eager else '')+'>'
def figure(path,caption,alt=None,cls=''):
 return f'<figure class="{cls}">{img(path,alt or caption)}<figcaption>{e(caption)}</figcaption></figure>'
def link(url,label,cls='text-link'):
 return f'<a class="{cls}" href="{url}">{label} <span aria-hidden="true">↗</span></a>'
def label(text):return '<span class="eyebrow">'+e(text)+'</span>'
def video(path,poster,caption,auto=False):
 if auto:
  el=f'<video data-ambient data-src="/{path}" muted loop playsinline preload="none" poster="/{poster}" aria-label="{e(caption)}"></video><button class="video-pause" data-pause aria-label="Play background film">Play film</button>'
 else:el=f'<video controls playsinline preload="none" poster="/{poster}" aria-label="{e(caption)}"><source src="/{path}" type="video/mp4"></video>'
 return f'<figure class="local-film">{el}<figcaption>{e(caption)}</figcaption></figure>'
STORIES=[
{'slug':'wildlife-wonders','title':'A world worth looking closer at.','category':'WILDLIFE / CONSERVATION','place':'Tunisia','image':P('556922215'),'desc':'From the smallest encounter to the wider landscape, Wildlife Wonders brings Tunisia’s natural heritage into view.','film':'oBRHiGLC0S4','credit':'The Dreamer × Zakher Bouragaoui · Tunisian Wonders','images':[P('555630946'),P('700708021'),P('556626056')], 'chapters':[('The living world, close up.','An owl in the shelter of stone. A reptile resting in sunlight. A bird in flight. Small encounters are a reminder that a landscape is more than its scenery. The camera gives those lives time and space within the frame.'),('A story made in the field.','Rabii describes working with wildlife ecologist Zakher Bouragaoui through the Tunisian Wonders initiative. The resulting film, Wildlife Wonders, follows a purpose central to The Dreamer: bringing Tunisia’s natural heritage into view.'),('Attention is a beginning.','The film connects visual storytelling with an interest in the living world. Its contribution here is an invitation to notice, to learn and to look again. No numerical conservation outcome is claimed for this project.')], 'source':'https://www.linkedin.com/posts/rabii-ben-brahim-007309141_wildlife-wonders-activity-7311423928600596482-iWgy'},
{'slug':'blue-future','title':'The sea connects the stories.','category':'DOCUMENTARY / CONSERVATION','place':'Mediterranean','image':P('526506341'),'desc':'A shared sea, different livelihoods. Blue Future follows work and lives tied to the Mediterranean.','film':'OyaSu8oF-D8','credit':'WWF / COGITO · Ante Gugić, Rabii Ben Brahim, Emanuele Quartarone and Beatrice Surano','images':[P('651451626'),P('650345189'),P('526763980')],'clip':'assets/projects/coastal-voices.mp4','poster':'assets/projects/coastal-voices.jpg', 'chapters':[('More than a horizon.','Seen from above, the coast becomes a meeting of rock, shallows and deep water. Seen from shore, it is also a place of work, knowledge and daily routines. These supplied photographs give the sea a human scale.'),('Three perspectives, one sea.','Blue Future is a collective documentary about sustainable livelihoods around the Mediterranean. WWF and COGITO are credited in its production. Rabii Ben Brahim appears among the four filmmaker credits, alongside Ante Gugić, Emanuele Quartarone and Beatrice Surano.'),('People belong in the frame.','The documentary’s environmental context includes the people whose work is connected to the sea. The coastal footage and photographs on this page extend that theme; they are selected from the supplied archive and are not presented as verified production stills from Blue Future.')], 'source':'https://www.wwf.it/area-stampa/blue-future-il-documentario-wwf-sui-lavori-blu/'},
{'slug':'djerba-between-sea-and-stone','title':'Between sea & stone.','category':'EXPEDITION / PHOTOGRAPHIC ESSAY','place':'Djerba, Tunisia','image':D('03-coastal-courtyard'),'desc':'Whitewashed courtyards, blue doorways and a filming day by the coast. A journey through the supplied Djerba field archive.','credit':'Field film and photographs supplied by The Dreamer','images':[D('02-blue-door'),D('04-rabii-filming'),D('07-team')],'clip':'assets/projects/djerba/coastline.mp4','poster':'assets/projects/djerba/03-coastal-courtyard.webp','chapters':[('A place in the details.','The visual story begins in the architecture: the curve of a courtyard, bright walls under open sky, and the blue of a weathered doorway. Together, these details hold a sense of place without needing a grand panorama.'),('On the other side of the camera.','The field photographs bring the filmmaking process into view. Rabii works with a camera, people gather for conversation, and the crew shares the space around them. The story of a place is also the story of meeting it.'),('The coast keeps moving.','A short coastal film gives the still photographs another rhythm. The supplied material is presented as a field essay, rather than a claim about a commissioned campaign or measurable conservation outcome.')], 'extra':[D('01-seaside-portrait'),D('05-interview'),D('06-land-rover'),D('08-camera-and-guest')]},
{'slug':'the-defender-journey','title':'The road is part of the story.','category':'COLLABORATION / EXPLORATION','place':'Tunisia','image':'assets/projects/defender-field.jpg','desc':'A journey across Tunisia for the Land Rover Defender campaign, with The Dreamer at the centre of the film.','film':'YkmgKAZFtXs','credit':'Land Rover Defender campaign · YKONE Tunis','images':['assets/about/01.jpg','assets/about/09.jpg','assets/projects/road-expedition.jpg'],'clip':'assets/projects/defender-field.mp4','poster':'assets/projects/defender-field.jpg','chapters':[('A different way to travel.','The road links coast, dunes and open ground. In this campaign, the journey is the setting for Rabii’s identity as The Dreamer: someone drawn to exploration and the places beyond the familiar view.'),('Exploration in context.','YKONE’s published case study identifies the Land Rover Defender campaign. The existing site connects the work with a road trip across Tunisia. The local clip shown here is supplied field footage, distinct from the linked campaign film.'),('Making room for the landscape.','Vehicle, traveller and place share the frame. The strongest moments let the surroundings carry the story: an open road, a pause beside the vehicle and another stretch of country ahead.')],'source':'https://ykone.com/portfolio/landrover-defender/'},
{'slug':'a-country-in-motion','title':'A country in motion.','category':'FILM / LANDSCAPE','place':'Tunisia','image':'assets/frames/tunisia-02.jpg','desc':'From forest to coast and open country: a cinematic journey through Tunisia.','film':'OtJVufo3IrA','credit':'The Dreamer · Tunisia film. Landscape images are frames from the supplied film.','images':['assets/frames/tunisia-06.jpg','assets/frames/tunisia-09.jpg','assets/frames/tunisia-14.jpg'],'chapters':[('Follow the landscape.','The Tunisia film moves between wide vistas and the details that make them particular. Its landscape frames are gathered here as a visual essay, keeping the distinction between moving-image stills and standalone photography clear.'),('Let the image breathe.','A coastline, a hillside and the light across open ground each ask for a different pace. In the film, movement links those views. On the page, space between the images lets each one stand on its own.'),('Another way to see home.','Tunisia remains at the heart of The Dreamer’s work. The journey is an invitation to discover the country through its landscape, its living world and the people connected to it.')]},
{'slug':'a-different-way-of-seeing','title':'A different way of seeing.','category':'COMMUNITY / PHOTOGRAPHY','place':'Tunisia','image':'assets/impact/field-mentoring.webp','desc':'Sharing the camera, sharing attention. Photography becomes a meeting point between people and place.','credit':'Supplied community footage and photography · CinémaJet, Zaghouan activity listed in the existing project archive','images':['assets/impact/photography-workshop.webp','assets/projects/community-field.jpg','assets/projects/cinemajet.jpg'],'clip':'assets/projects/community-field.mp4','poster':'assets/projects/community-field.jpg','chapters':[('The camera can be a meeting point.','In the supplied photographs, participants gather around the process of making an image. Watching, talking and taking turns become part of the story. The camera is a practical way to share attention.'),('A place through its people.','The existing project archive describes Rabii’s participation in the CinémaJet photography programme in Zaghouan. The activity invites a view of the city through the residents who give it life.'),('Beyond a finished photograph.','The images on this page document conversation and participation. They show a process, rather than a quantified impact claim. The relationships around the frame matter alongside the photograph itself.')]}]
FILMS=[('wildlife-wonders','Wildlife Wonders','oBRHiGLC0S4','DOCUMENTARY / TUNISIA',P('556922215'),'A closer look at Tunisia’s natural heritage.'),('blue-future','Blue Future','OyaSu8oF-D8','DOCUMENTARY / WWF',P('526506341'),'Mediterranean livelihoods and sustainable futures.'),('tunisia','Tunisia','OtJVufo3IrA','FIELD FILM / TUNISIA','assets/frames/tunisia-02.jpg','A country seen through movement and light.'),('defender','Land Rover Defender','YkmgKAZFtXs','CAMPAIGN / YKONE','assets/projects/defender-field.jpg','The road, the landscape and the journey.'),('bizerte','Bizerte','uyeXpLjqgxw','FIELD FILM / TUNISIA','assets/frames/tunisia-09.jpg','A visual exploration of Bizerte.'),('el-kef','El Kef','xKpNfEQQrWE','FIELD FILM / TUNISIA','assets/frames/tunisia-06.jpg','Place and sustainable tourism.'),('torda','Torda','7ftfKXuN38o','FIELD FILM / BIODIVERSITY','assets/story/field-life.jpg','A field film connected to biodiversity.')]
NOTES=[('small-worlds','The wild, at another scale.',P('555826408'),'A small reptile, a warm stone, an entire world of detail.','Look closely at the supplied reptile photographs and the landscape changes scale. Texture takes the place of a wide horizon; a small movement becomes the centre of the image. These frames offer a quieter way into the wildlife archive.','Wildlife'),('a-line-of-blue','A line of blue.',P('526215548'),'Reading the coast through colour, rock and water.','From above, the shoreline is a drawing in colour. Pale stone meets turquoise shallows before giving way to deeper blue. The supplied coastal photographs let the shape of the shore carry the story.','Landscapes'),('behind-the-frame','On the other side of the frame.',P('526285315'),'The image begins before the shutter.','The archive includes photographs of the process itself: a camera raised, a figure watching, equipment in the field. They bring a human presence to the finished image without inventing the circumstances of a particular shoot.','Behind the Lens')]
NAV=[('Stories','stories'),('Films','films'),('Photography','photography'),('Expeditions','expeditions'),('Conservation','conservation'),('About','about')]
SECOND=[('Collaborations','collaborations'),('Speaking & Media','speaking'),('Prints','prints'),('Field Notes','field-notes'),('Contact','contact')]
PAGES=[]
def doc(route,title,desc,body,image='assets/hero-new/poster.webp',article=False):
 nav=''.join(f'<a href="/{slug}/"'+(' aria-current="page"' if route.strip('/').split('/')[0]==slug else '')+f'>{name}</a>' for name,slug in NAV)
 secondary=''.join(link('/'+slug+'/',name,'') for name,slug in SECOND)
 schema={'@context':'https://schema.org','@type':'Article' if article else 'WebPage','headline' if article else 'name':title,'description':desc,'url':ORIGIN+route,'image':ORIGIN+'/'+image}
 if article:schema.update(author={'@type':'Organization','name':'The Dreamer'},about={'@type':'Person','name':'Rabii Ben Brahim'})
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#080808"><title>{e(title)} | The Dreamer</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{ORIGIN+route}"><meta property="og:type" content="{'article' if article else 'website'}"><meta property="og:title" content="{e(title)} | The Dreamer"><meta property="og:description" content="{e(desc)}"><meta property="og:image" content="{ORIGIN+'/'+image}"><meta property="og:url" content="{ORIGIN+route}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/logo.png"><link rel="stylesheet" href="/editorial.css"><script type="application/ld+json">{json.dumps(schema)}</script><script defer src="/editorial.js"></script></head><body class="{'front-page' if route=='/' else 'inside-page'}"><a class="skip" href="#main">Skip to content</a><header class="publication-header"><a class="brand" href="/" aria-label="The Dreamer — home"><img src="/assets/logo.png" width="47" height="47" alt=""><span>THE DREAMER<span class="brand-sub">WILD & FREE</span></span></a><nav class="desktop-nav" aria-label="Main navigation">{nav}</nav><button id="menu-toggle" class="menu-toggle" aria-controls="publication-menu" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button></header><dialog id="publication-menu" class="menu-dialog" aria-label="Explore The Dreamer"><div class="menu-top">{label('THE DREAMER / EXPLORE')}<button data-close aria-label="Close menu">Close ×</button></div><nav aria-label="Full navigation">{nav}</nav><div class="menu-secondary">{secondary}</div><p>Stories from the wild.<br>Rabii Ben Brahim.</p></dialog><main id="main">{body}</main><footer><div class="footer-top"><div>{label('THE DREAMER / RABII BEN BRAHIM')}<p class="footer-statement">Keep looking closer.</p><p>Wildlife. People. Place.<br>Film and photography from the field.</p></div><nav aria-label="Footer navigation">{secondary}</nav><div class="social-links">{link(IG,'Instagram','')}{link('https://www.youtube.com/@thedreamerwildandfree','YouTube','')}{link('https://www.linkedin.com/in/rabii-ben-brahim-007309141','LinkedIn','')}</div></div><div class="footer-bottom"><span>© 2026 THE DREAMER</span>{link('https://auradigitalworks.com/','Made by AuraDigital','')}{link('#main','Back to the beginning','')}</div></footer><dialog id="media-viewer" class="media-dialog" aria-label="Media viewer"><button class="viewer-close" data-close aria-label="Close viewer">Close ×</button><div id="viewer-content"></div><div class="viewer-navigation"><button id="photo-prev" aria-label="Previous photograph">←</button><p id="viewer-caption" aria-live="polite"></p><button id="photo-next" aria-label="Next photograph">→</button></div></dialog></body></html>'''
 path=ROOT/route.strip('/')/'index.html';path.parent.mkdir(parents=True,exist_ok=True);path.write_text(html);PAGES.append(route)
def intro(kicker,title,text):return f'<section class="page-intro wrap">{label(kicker)}<h1>{title}</h1><p>{text}</p></section>'
def sectionhead(kicker,title,url=None,cta='Explore all'):
 return f'<div class="section-heading"><div>{label(kicker)}<h2>{title}</h2></div>{link(url,cta) if url else ""}</div>'
def tile(s,large=False):
 return f'<article class="story-tile {"large-tile" if large else ""}"><a href="/stories/{s["slug"]}/">{img(s["image"],s["desc"])}{label(s["category"])}<h3>{s["title"]}</h3><p>{s["place"]} <span aria-hidden="true">↗</span></p></a></article>'
def filmcard(f,featured=False):
 slug,title,id,cat,path,desc=f
 return f'<article class="film-card {"featured-film" if featured else ""}"><a class="film-poster" href="/films/{slug}/" data-film="{id}" data-title="{title}">{img(path,desc)}<span class="play-mark" aria-hidden="true">▷</span><span class="film-overlay">{label(cat)}<strong>{title}</strong><span>WATCH FILM →</span></span></a></article>'
def photocard(n):
 title,alt,cat=PHOTO[n]
 return f'<figure class="photo-entry" data-category="{cat}"><a href="/{P(n)}" data-photo data-caption="{e(title)} — {e(cat)} · The Dreamer photo archive">{img(P(n),alt)}</a><figcaption><span>{title}</span><span>{cat}</span></figcaption></figure>'
def journeycard(slug,title,path,desc):
 return f'<article class="journey-card"><a href="/expeditions/{slug}/">{img(path,desc)}{label("FIELD JOURNEY / TUNISIA")}<h3>{title}</h3><p>{desc} <span aria-hidden="true">↗</span></p></a></article>'
# Front page
home=f'''<section class="opening"><video id="opening-film" data-ambient data-src="/assets/hero-new/editorial-loop.mp4" data-mobile="/assets/hero-new/editorial-mobile.mp4" muted loop playsinline preload="none" poster="/assets/hero-new/editorial-poster.webp" aria-label="The Dreamer’s cinematic landscape film of Tunisia"></video><div class="opening-shade"></div><div class="opening-copy">{label('RABII BEN BRAHIM / THE DREAMER')}<h1>Stories from<br><em>the wild.</em></h1><p>Wildlife Filmmaker · Photographer · Conservation Storyteller</p></div><div class="opening-bottom"><a href="#cover">SCROLL TO EXPLORE ↓</a><div><a href="/films/tunisia/" data-film="OtJVufo3IrA" data-title="Tunisia">WATCH THE FILM ↗</a><button data-pause aria-label="Play background film">Play film</button></div></div></section>'''
home+=f'''<section class="cover paper" id="cover"><div class="cover-layout wrap"><div class="cover-copy">{label('THE COVER STORY / WILDLIFE')}<span class="issue-number">01 — A CLOSER WORLD</span><h2>A world<br>worth<br><em>seeing.</em></h2><p>{STORIES[0]['desc']}</p>{link('/stories/wildlife-wonders/','Explore the story')}</div><a class="cover-image" href="/stories/wildlife-wonders/">{img(P('556922215'),'Owl sheltered in a rocky hollow')}<span class="image-footnote">WILDLIFE WONDERS / THE DREAMER</span></a></div></section>'''
home+=f'<section class="wrap section">{sectionhead("FROM THE FIELD","Latest stories.","/stories/","All stories")}<div class="latest-grid">{tile(STORIES[2],True)}<div>{tile(STORIES[1])}{tile(STORIES[3])}</div></div></section>'
home+=f'<section class="frame-section">{label("FRAME FROM THE WILD")}{figure(P("645836414"),"Last light over the herd. Elephants silhouetted against the setting sun.","Elephants silhouetted against the setting sun")}<div class="frame-note"><h2>A moment.<br>A whole world.</h2><p>One frame from The Dreamer’s supplied wildlife archive. The last light gives way to silhouettes, and the herd holds the horizon.</p>{link("/photography/","View photography")}</div></section>'
home+=f'<section class="wrap section film-section">{sectionhead("THE MOVING IMAGE","Stories in motion.","/films/","All films")}{filmcard(FILMS[0],True)}<div class="three-grid film-strip">'+''.join(filmcard(f) for f in FILMS[1:4])+'</div></section>'
home+=f'<section class="paper section"><div class="wrap">{sectionhead("GO WHERE THE STORY BEGINS","Expeditions.","/expeditions/","Explore the journeys")}<div class="two-grid">{journeycard("tunisia","Tunisia","assets/frames/tunisia-02.jpg","Forest, coast and open country.")}{journeycard("djerba","Djerba",D("03-coastal-courtyard"),"Between sea and stone.")}</div></div></section>'
home+=f'<section class="wrap section">{sectionhead("A CURATED ARCHIVE","The world, held still.","/photography/","Explore photography")}<div class="photo-preview">'+''.join(photocard(n) for n in ['469728961','526506341','700708021'])+'</div></section>'
home+=f'<section class="mission">{img("assets/impact/field-mentoring.webp","Rabii sharing photography with young participants")}<div class="mission-copy">{label("CONSERVATION / PEOPLE / PLACE")}<h2>See a place.<br><em>Care for its story.</em></h2><p>Bringing Tunisia’s natural and cultural heritage into view — through wildlife films, coastal voices and the people behind the images.</p>{link("/conservation/","Discover the work")}</div></section>'
home+=f'<section class="paper section"><div class="wrap">{sectionhead("BETWEEN THE BIG STORIES","Field notes.","/field-notes/","Read the notes")}<div class="three-grid">'+''.join(f'<article class="note-card"><a href="/field-notes/{s}/">{img(im,d)}{label(cat)}<h3>{t}</h3><p>{d}</p></a></article>' for s,t,im,d,body,cat in NOTES)+'</div></div></section>'
home+=f'<section class="wrap section about-preview"><div>{img("assets/about/07.jpg","Rabii standing in the light of sunrise")}</div><div>{label("THE STORYTELLER")}<h2>Rabii<br>Ben Brahim.</h2><p>Filmmaker, photographer and the voice behind The Dreamer. A journey rooted in curiosity, and a commitment to bringing Tunisia’s natural and cultural heritage closer.</p>{link("/about/","Meet the Dreamer")}</div></section>'
home+=f'<section class="wrap section collaborators">{sectionhead("STORIES MADE TOGETHER","Selected collaborations.","/collaborations/","View the projects")}<div class="three-grid">'+''.join(f'<a class="collaboration-tile" href="/stories/{STORIES[i]["slug"]}/">{img(STORIES[i]["image"],STORIES[i]["desc"])}{label(name)}<h3>{context}</h3></a>' for i,name,context in [(3,'LAND ROVER / YKONE TUNIS','Exploration in motion.'),(1,'WWF / COGITO','A shared blue future.'),(0,'TUNISIAN WONDERS','The living world, closer.')])+'</div></section>'
home+=f'<section class="final-cta">{img("assets/about/09.jpg","Rabii beside a vehicle overlooking the landscape")}<div>{label("THE NEXT CHAPTER")}<h2>Every place<br><em>has a story.</em></h2><p>Let’s tell the ones worth remembering.</p>{link("/contact/","Work with Rabii")}</div></section>'
doc('/','Stories from the wild','The Dreamer: an editorial world of wildlife films, photography and field stories by Rabii Ben Brahim.',home)
# Archive and long-form stories
body=intro('THE DREAMER / EDITORIAL','Stories from the field.','Wildlife, coastlines, journeys and the people who make a place. Explore a story, then stay with it.')+'<section class="wrap section"><div class="stories-grid">'+''.join(tile(s) for s in STORIES)+'</div></section>'
doc('/stories/','Stories','Visual stories from The Dreamer’s films and field archive.',body)
for i,s in enumerate(STORIES):
 body=f'<section class="story-opening">{img(s["image"],s["desc"],eager=True)}<div>{label(s["category"])}<h1>{s["title"]}</h1><p>{s["place"]} / THE DREAMER</p></div></section><section class="article-intro measure">{label("A VISUAL STORY")}<p class="standfirst">{s["desc"]}</p></section>'
 for j,(heading,paragraph) in enumerate(s['chapters']):
  body+=f'<section class="measure article-copy">{label(f"0{j+1} / FROM THE FIELD")}<h2>{heading}</h2><p>{paragraph}</p></section>'
  body+=figure(s['images'][j], ('Frame from the Tunisia film.' if s['slug']=='a-country-in-motion' else 'From the supplied Dreamer field archive.'),cls='essay-figure wrap')
  if j==1 and s.get('clip'):body+='<div class="wrap essay-video">'+video(s['clip'],s['poster'],'Supplied field footage / '+s['place'])+'</div>'
 if s.get('extra'):body+='<section class="wrap two-grid essay-spread">'+''.join(figure(p,'Djerba / field photography') for p in s['extra'])+'</section>'
 if s.get('film'):
  f=next(f for f in FILMS if f[2]==s['film']);body+=f'<section class="wrap section">{sectionhead("WATCH THE STORY","The film.")}{filmcard(f,True)}</section>'
 body+=f'<section class="measure credits">{label("CREDITS / CONTEXT")}<p>{s["credit"]}</p>'+ (link(s['source'],'Project source') if s.get('source') else '')+'</section>'
 nxt=STORIES[(i+1)%len(STORIES)];body+=f'<section class="paper next-story wrap section">{label("NEXT STORY")}<h2>{link("/stories/"+nxt["slug"]+"/",nxt["title"],"")}</h2></section>'
 doc('/stories/'+s['slug']+'/',s['title'],s['desc'],body,s['image'],True)
# Film catalogue and pages
doc('/films/','Films','Documentaries, campaigns and field films by The Dreamer.',intro('THE DREAMER / FILMS','Stories in motion.','Nature, Tunisia and the people whose lives are tied to place.')+'<section class="wrap section">'+filmcard(FILMS[0],True)+'<div class="two-grid film-strip">'+''.join(filmcard(f) for f in FILMS[1:])+'</div></section>')
for f in FILMS:
 slug,title,id,cat,path,desc=f
 body=intro(cat,title,desc)+f'<section class="wrap film-watch"><button class="watch-inline" data-inline-film="{id}" data-title="{title}">{img(path,desc,eager=True)}<span class="play-mark" aria-hidden="true">▷</span><span class="watch-label">PLAY FILM</span></button><noscript>{link("https://www.youtube.com/watch?v="+id,"Watch on YouTube")}</noscript></section><section class="measure credits"><p>{desc}</p>'+link('https://www.youtube.com/watch?v='+id,'Watch on YouTube')+'</section>'
 matches=[s for s in STORIES if s.get('film')==id]
 if matches:body+=f'<section class="wrap section">{sectionhead("BEYOND THE SCREEN","Explore the story.")}{tile(matches[0])}</section>'
 doc('/films/'+slug+'/',title,desc,body,path)
# Photography, preserving all original frames
CATS=['Wildlife','People','Landscapes','Conservation','Black & White','Behind the Lens']
def catslug(c):return c.lower().replace(' & ','-and-').replace(' ','-')
for category in ['All']+CATS:
 route='/photography/' if category=='All' else '/photography/'+catslug(category)+'/'
 selected=[n for n,v in PHOTO.items() if category=='All' or v[2]==category]
 filters='<nav class="photo-filters" aria-label="Photography categories">'+''.join(f'<a href="'+('/photography/' if c=='All' else '/photography/'+catslug(c)+'/')+'"'+(' aria-current="page"' if c==category else '')+'>'+c+'</a>' for c in ['All']+CATS)+'</nav>'
 body=intro('THE DREAMER / PHOTOGRAPHY','The world, held still.' if category=='All' else category+'.','A curated view of the supplied photo archive. Open any frame to see its full composition.')+f'<section class="wrap">{filters}<div class="photo-grid">'+''.join(photocard(n) for n in selected)+'</div></section>'
 doc(route,'Photography' if category=='All' else category+' photography','Photography from The Dreamer’s field archive: '+category+'.',body,P(selected[0]))
# Expeditions, only evidenced destinations
doc('/expeditions/','Expeditions','Documented journeys through Tunisia and the Djerba field archive.',intro('THE DREAMER / JOURNEYS','Go where the story begins.','A field archive of places, people and encounters. Each journey opens another way of seeing.')+f'<section class="wrap section two-grid">{journeycard("tunisia","Tunisia","assets/frames/tunisia-02.jpg","From forest to coast and open country.")}{journeycard("djerba","Djerba",D("03-coastal-courtyard"),"Whitewashed walls, blue doorways and a filming day by the sea.")}</section>')
for slug,title,path,ids in [('tunisia','Tunisia','assets/frames/tunisia-02.jpg',[4,0,1,3,5]),('djerba','Djerba',D('03-coastal-courtyard'),[2])]:
 body=f'<section class="story-opening">{img(path,title+" field journey",eager=True)}<div>{label("EXPEDITION / TUNISIA")}<h1>{title}.</h1></div></section><section class="measure article-copy"><h2>A place, through its stories.</h2><p>'+('Explore Tunisia through documented films, wildlife stories, coastal livelihoods and community photography.' if slug=='tunisia' else 'The supplied Djerba archive brings together architecture, coastline and the process of filming on location.')+'</p>'+link('https://www.openstreetmap.org/search?query='+title,'Explore the location on a map')+'</section><section class="wrap section stories-grid">'+''.join(tile(STORIES[i]) for i in ids)+'</section>'
 if slug=='djerba':body+='<div class="wrap essay-video">'+video('assets/projects/djerba/coastline.mp4','assets/projects/djerba/03-coastal-courtyard.webp','Djerba / supplied coastal field film')+'</div>'
 doc('/expeditions/'+slug+'/',title+' expedition','The Dreamer’s '+title+' field journey.',body,path)
# Conservation
body=f'<section class="story-opening">{img("assets/impact/field-mentoring.webp","Rabii introducing young participants to photography",eager=True)}<div>{label("THE DREAMER / CONSERVATION")}<h1>Look closer.<br>Care more.</h1></div></section><section class="measure article-copy"><p class="standfirst">A place becomes harder to ignore when its story is seen.</p><p>Rabii describes his work as a way to draw attention to Tunisia’s natural and cultural heritage. Wildlife, coastal livelihoods and the people connected to place belong in the same conversation.</p></section><section class="wrap section">{sectionhead("THE WORK IN CONTEXT","Nature. People. Place.")}<div class="three-grid">'+''.join(tile(STORIES[i]) for i in [0,1,5])+'</div></section>'
body+='<section class="wrap section">'+video('assets/impact/field-stories.mp4','assets/impact/impact-opening.jpg','Field and community / supplied footage')+'<div class="two-grid">'+video('assets/impact/community-coast.mp4','assets/impact/community-coast-poster.webp','Life along the coast')+video('assets/impact/nature-value.mp4','assets/impact/nature-value-poster.webp','The value of nature / silent supplied footage')+'</div></section><section class="measure article-copy"><h2>Heritage is a living story.</h2><p>Alongside wildlife and landscape, the field archive records architecture, conversations and community photography. These stories invite attention; they do not substitute for verified measures of conservation impact.</p>'+link('/stories/djerba-between-sea-and-stone/','Explore the Djerba field story')+'</section>'
doc('/conservation/','Conservation','Wildlife, cultural heritage and the people connected to place: The Dreamer’s conservation storytelling.',body,'assets/impact/field-mentoring.webp')
# Journal
body=intro('THE DREAMER / FIELD NOTES','Between the big stories.','Short editorial observations from the supplied image archive. Another way into the field.')+'<section class="wrap section three-grid">'+''.join(f'<article class="note-card"><a href="/field-notes/{s}/">{img(im,d)}{label(cat)}<h2>{t}</h2><p>{d}</p></a></article>' for s,t,im,d,b,cat in NOTES)+'</section>'
doc('/field-notes/','Field notes','Short visual observations from The Dreamer photo archive.',body)
for slug,title,path,desc,text,cat in NOTES:
 body=intro('FIELD NOTE / '+cat.upper(),title,desc)+figure(path,title,cls='wrap essay-figure')+f'<section class="measure article-copy"><p>{text}</p>{link("/photography/"+catslug(cat)+"/","Continue through the archive")}</section>'
 doc('/field-notes/'+slug+'/',title,desc,body,path,True)
# The storyteller: all supplied About photographs remain in the experience
body=f'<section class="about-opening wrap">{img("assets/about/07.jpg","Rabii at sunrise",eager=True)}<div>{label("THE STORYTELLER")}<h1>Rabii<br>Ben Brahim.</h1><p>Wildlife Filmmaker.<br>Photographer.<br>Conservation Storyteller.</p></div></section><section class="measure article-copy"><h2>Curiosity became a journey.</h2><p>Rabii has spoken about watching documentaries with his father and spending time near the forest with his uncle. Those early experiences shaped the stories he would choose to tell. He began exploring Tunisia with a camera and a backpack.</p><p>Through The Dreamer, film and photography become a way to draw attention to Tunisia’s natural and cultural heritage — its forests, coast, open landscapes, wildlife and the people connected to them.</p>{link("https://www.discovertunisia.com/en/success-stories/rabii-ben-brahim","Read the early journey")}</section>'
body+='<section class="wrap about-archive two-grid">'+''.join(figure('assets/about/'+f'{n:02}.jpg','The Dreamer / supplied field photograph') for n in [1,2,3,4,5,6,8,9,10,11,12,13])+'</section>'
body+='<section class="wrap section two-grid">'+video('assets/about/tunisia.mp4','assets/about/03.jpg','Tunisia / supplied portrait film')+video('assets/about/wildlife.mp4','assets/about/02.jpg','Wildlife / supplied portrait film')+'</section>'
body+=f'<section class="measure article-copy"><h2>Look closer. Go further.</h2><p>Selected work includes Wildlife Wonders, Blue Future and the Land Rover Defender campaign with YKONE. Speaking and media appearances open another window onto the person behind the images.</p>{link("/films/","Explore the films")}{link("/speaking/","Hear the storyteller")}</section>'
doc('/about/','Rabii Ben Brahim','Meet Rabii Ben Brahim, filmmaker, photographer and the voice behind The Dreamer.',body,'assets/about/07.jpg')
# Collaborations: context instead of logo wall
body=intro('THE DREAMER / COLLABORATIONS','Stories made together.','Campaigns, documentaries, independent films and community projects. The work, and the people behind it.')+'<section class="wrap section stories-grid">'+''.join(tile(STORIES[i]) for i in [3,0,1,2,5])+'</section>'
body+='<section class="wrap section">'+sectionhead('ON SCREEN / IN THE COMMUNITY','Beyond the camera.')+'<div class="two-grid">'+figure('assets/projects/where-is-diana.jpg','Where Is Diana? / 2024 · Directed by Sami Chaffai · Featuring Rabii Ben Brahim. Acting credit.')+figure('assets/projects/cinemajet.jpg','CinémaJet / Zaghouan, Tunisia · Photography activity.')+'</div>'+link('https://youtu.be/dT68BX8jonk','Sadeem — television appearance')+'</section>'
body+='<section class="wrap section">'+sectionhead('SUPPLIED FIELD FOOTAGE','The journey continues.')+'<div class="two-grid">'+video('assets/projects/road-expedition.mp4','assets/projects/road-expedition.jpg','On the road / supplied footage')+video('assets/story/desert-road.mp4','assets/story/desert-road.jpg','Desert road / supplied footage')+video('assets/story/field-life.mp4','assets/story/field-life.jpg','The living world / supplied footage')+video('assets/story/sea-journey.mp4','assets/story/sea-journey.jpg','The sea / supplied footage')+'</div></section>'
doc('/collaborations/','Collaborations','Selected films, campaigns and community projects from The Dreamer.',body)
# Speaking and media, retaining established content
body=intro('THE DREAMER / SPEAKING & MEDIA','Stories worth sharing.','Conversations about nature, film and seeing a place with fresh eyes.')+'<section class="wrap section two-grid">'+video('assets/speaking/clip-01.mp4','assets/projects/community-field.jpg','A moment from the conversation')+video('assets/speaking/clip-03.mp4','assets/projects/community-field.jpg','The Dreamer speaks')+'</section>'
body+='<section class="wrap section">'+sectionhead('INTERVIEWS / CONVERSATIONS','The voice behind the images.')+'<div class="three-grid">'+''.join(f'<article class="interview"><h3>{t}</h3><a class="interview-play" href="https://www.youtube.com/watch?v={id}" data-film="{id}" data-title="{t}">Play conversation ▷</a></article>' for t,id in [('A conversation with Rabii','7cYfRkddQOE'),('Behind the microphone','poFk6c6C25Y'),('Radio Cap FM','5ZJtvU-VOjw')])+'</div></section>'
body+='<section class="measure article-copy"><h2>On stage. In conversation.</h2>'+link('https://www.ted.com/talks/rabii_ben_brahim_what_i_can_do_in_tunisia','TEDxDjerba — What I can do in Tunisia (2017)')+link('https://www.arabnews.fr/node/194521/culture','Arab News en français — The Dreamer')+link('https://jninetelhafsia.bluefish.me/','Wildlife Wonders — Jninet El Hafsia screening')+link('https://youtu.be/AcNYeD8vvbw','Kïff Dealer interview')+'<p>For interviews, panels, screenings, universities and creative events.</p>'+link('/contact/','Invite The Dreamer')+'</section>'
doc('/speaking/','Speaking & Media','Hear the stories behind The Dreamer’s films and photography.',body)
# No invented commerce or receiving address
body=intro('THE DREAMER / FINE ART','A frame that stays with you.','A first look at a future print collection. Selected photographs, held beyond the screen.')+'<section class="wrap photo-grid">'+''.join(photocard(n) for n in ['526506341','526215548','469728961','556922215','469683747','555630946'])+'</section><section class="measure article-copy"><h2>Selected by the artist.</h2><p>The print collection is in preparation. Editions, sizes, paper, final prices and delivery will be confirmed by Rabii. Ask about a photograph or future availability.</p>'+link(IG,'Ask Rabii about a print')+'</section>'
doc('/prints/','Fine Art Prints','Explore a preview of The Dreamer’s future fine art print collection.',body,P('526506341'))
body=intro('THE DREAMER / CONTACT','Every story starts somewhere.','For films, conservation work, creative partnerships, photography, speaking and print enquiries.')+f'<section class="wrap contact-layout"><div>{img("assets/about/09.jpg","Rabii in the field beside a vehicle")}</div><div>{label("WORK WITH RABII")}<h2>Let’s tell<br>the next story.</h2><p>Share your idea, your place and what you hope to bring into view.</p>{link(IG,"Start a conversation on Instagram")}<p class="contact-note">Rabii’s direct inquiry address is being confirmed. His public Instagram profile is the current contact channel.</p><div class="contact-topics"><span>Documentary production</span><span>Conservation storytelling</span><span>Photography & campaigns</span><span>Speaking & media</span></div></div></section>'
doc('/contact/','Contact','Work with Rabii Ben Brahim on films, photography, conservation stories and creative partnerships.',body,'assets/about/09.jpg')
# SEO and custom error route
person={'@context':'https://schema.org','@type':'Person','name':'Rabii Ben Brahim','alternateName':'The Dreamer','url':ORIGIN+'/about/','sameAs':[IG,'https://www.linkedin.com/in/rabii-ben-brahim-007309141'],'jobTitle':'Wildlife filmmaker and photographer'}
p=ROOT/'about/index.html';p.write_text(p.read_text().replace('</head>','<script type="application/ld+json">'+json.dumps(person)+'</script></head>'))
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+ORIGIN+r+'</loc></url>' for r in PAGES)+'</urlset>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n')
error=intro('THE DREAMER / 404','A little off the trail.','This page could not be found. There are more stories to discover.')+'<section class="wrap section">'+link('/stories/','Explore stories')+'</section>'
doc('/not-found/','Page not found','Return to The Dreamer stories.',error)
(ROOT/'404.html').write_text((ROOT/'not-found/index.html').read_text())
print('Generated',len(PAGES),'editorial pages with',len(PHOTO),'photographs.')
